spring:
  datasource:
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/hospitalmanagementsystem
    
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

       

       